# Generated by Django 4.0.5 on 2022-06-15 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdtWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semaine', models.CharField(max_length=10, unique=True)),
                ('DebutSeance', models.DateTimeField()),
                ('FinSeance', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Edt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeSeance', models.CharField(max_length=10)),
                ('NomSession', models.CharField(max_length=100)),
                ('NomMatiere', models.CharField(max_length=200)),
                ('ThemeSeance', models.CharField(max_length=200)),
                ('IntervenantNom', models.CharField(max_length=100)),
                ('IntervenantPrenom', models.CharField(max_length=100)),
                ('DebutSeance', models.DateTimeField()),
                ('FinSeance', models.DateTimeField()),
                ('NomSalle', models.CharField(max_length=100)),
                ('Semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edt.edtweek', to_field='Semaine')),
            ],
        ),
    ]
