# Generated by Django 4.0.5 on 2022-06-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0002_alter_edt_semaine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edt',
            name='Semaine',
            field=models.CharField(max_length=10),
        ),
    ]
